### ISSUE TITLE
error with new openssl.js API

### ISSUE THREAD

**Issue by kulikov-a** [CyberShadow/keygen.js#2]
Hi!
openssl.js api updated. With new openssl.js version keygen.js throws error (WASI Exit error: 0)

**Comment by CyberShadow** [comment]
keygen.js was developed and tested against this specific version of openssl.js:
https://github.com/DigitalArsenal/openssl.js/tree/f426f9f9b461e3691d4e7d88857dea03c4457b6b

I suggest that you use that version. (If you clone with `--recursive`, git will fetch that version automatically.)

**Comment by kulikov-a** [comment]
Thanks! works fine
